const recipes=[{name:"Pâtes crémeuses aux champignons",emoji:"🍝",time:"25 min",match:87,cat:"Plats"},{name:"Poulet curry coco",emoji:"🍛",time:"35 min",match:100,cat:"Cuisine du monde"},{name:"Bowl quinoa avocat",emoji:"🥗",time:"20 min",match:92,cat:"Healthy"},{name:"Lasagnes maison",emoji:"🍲",time:"1 h",match:60,cat:"Plats"},{name:"Tacos maison",emoji:"🌮",time:"30 min",match:80,cat:"Cuisine du monde"},{name:"Fondant chocolat",emoji:"🍰",time:"40 min",match:70,cat:"Desserts"}];
const defaults={favorites:[],liked:[],fridge:["🍗 Poulet","🍅 Tomates","🥚 Œufs","🧀 Parmesan","🍄 Champignons"],menu:[["Lun","🥗 Salade César","🍛 Poulet curry"],["Mar","🌯 Wrap poulet","🍝 Pâtes pesto"],["Mer","🍲 Bowl quinoa","🍕 Pizza maison"],["Jeu","🥣 Soupe légumes","🍲 Ratatouille"],["Ven","🥗 Salade composée","🌮 Tacos maison"],["Sam","🍔 Burger maison","🍝 Pâtes crémeuses"],["Dim","🥞 Brunch","🍲 Gratin dauphinois"]],dark:false};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem("miamState")||"{}")); state.page="home";state.favorites=new Set(state.favorites);state.liked=new Set(state.liked);state.chat=[];
const app=document.querySelector("#app"),title=document.querySelector("#pageTitle"),subtitle=document.querySelector("#subtitle");
const nav={home:["Bonjour 👋","Une idée pour aujourd'hui ?"],discover:["Découvrir","Trouve ton prochain coup de cœur"],fridge:["Mon frigo 🧊","Tes ingrédients disponibles"],menu:["Mon menu 📅","Organise tes repas simplement"],profile:["Ma bibliothèque 👤","Tout ton univers cuisine"],assistant:["Assistant Miam ✨","Ton copilote en cuisine"]};
function save(){localStorage.setItem("miamState",JSON.stringify({...state,favorites:[...state.favorites],liked:[...state.liked],page:"home",chat:[]}));}
function toast(t){let e=document.querySelector("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),2200)}
function setPage(p){state.page=p;[title.textContent,subtitle.textContent]=nav[p];document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));render()}
function card(r){return `<article class="recipe-card" onclick="openRecipe('${r.name}')"><div class="recipe-img">${r.emoji}</div><div class="pad"><h3>${r.name}</h3><div class="small">⏱ ${r.time} · 🧊 ${r.match}%</div></div></article>`}
function home(){return `<input class="search" placeholder="🔎 Rechercher une recette..." oninput="search(this.value)"><section class="hero"><h2>Jamais goûté ? 🎲</h2><p>Découvre une recette qui pourrait devenir ton nouveau coup de cœur.</p><button class="secondary pressable" style="margin-top:13px" onclick="surprise()">Surprends-moi</button><div class="emoji">🎲</div></section><section class="section"><div class="section-head"><h2>✨ Pour toi</h2><button class="link" data-page="discover">Voir tout</button></div><div class="cards">${recipes.slice(0,5).map(card).join("")}</div></section><section class="section"><div class="row-card" data-page="fridge"><div class="food-icon">🧊</div><div class="grow"><h3>Avec ton frigo</h3><p>Tu peux préparer 12 recettes.</p></div><span>›</span></div><div class="row-card" data-page="menu"><div class="food-icon">📅</div><div class="grow"><h3>Ce soir</h3><p>🍛 Poulet curry coco</p></div><span>›</span></div></section>`}
function discover(){let c=[["🥗","Entrées"],["🍝","Plats"],["🍰","Desserts"],["🌱","Healthy"],["🌍","Cuisine du monde"],["⚡","Rapide"],["💰","Petit budget"],["🥦","Végétarien"]];return `<input class="search" placeholder="🔎 Pizza, poulet, pâtes..." oninput="search(this.value)"><div class="grid">${c.map(x=>`<div class="category" onclick="filterCat('${x[1]}')"><div class="cat-icon">${x[0]}</div>${x[1]}</div>`).join("")}</div><section class="section"><h2>🔥 Tendances</h2><div class="grid">${recipes.map(card).join("")}</div></section>`}
function fridge(){return `<div class="tabs"><button class="tab active">Mes aliments</button><button class="tab" onclick="showSuggestions()">Que cuisiner ?</button></div><input class="search" placeholder="🔎 Ajouter un aliment puis Entrée" onkeydown="if(event.key==='Enter')addFood(this.value)"><button class="primary pressable" onclick="let x=prompt('Quel aliment veux-tu ajouter ?');if(x)addFood(x)">＋ Ajouter un aliment</button><section class="section"><h2>⚠️ À consommer rapidement</h2><div class="row-card"><div class="food-icon">🍗</div><div class="grow"><h3>Poulet</h3><p>À consommer dans 1 jour</p></div><span class="badge danger">Urgent</span></div><div class="row-card"><div class="food-icon">🍅</div><div class="grow"><h3>Tomates</h3><p>À consommer dans 2 jours</p></div><span class="badge warning">Bientôt</span></div></section><section class="section"><h2>Mon inventaire (${state.fridge.length})</h2>${state.fridge.map((x,i)=>`<div class="row-card"><div class="grow">${x}</div><button class="link" onclick="removeFood(${i})">Retirer</button></div>`).join("")}</section>`}
function sugg(){return `<div class="tabs"><button class="tab" data-page="fridge">Mes aliments</button><button class="tab active">Que cuisiner ?</button></div><h2>Que puis-je cuisiner ? 🥬</h2><p>Basé sur les ingrédients présents dans ton frigo.</p><section class="section">${recipes.map(r=>`<div class="row-card" onclick="openRecipe('${r.name}')"><div class="food-icon">${r.emoji}</div><div class="grow"><h3>${r.name}</h3><p>${r.match===100?"Tous les ingrédients disponibles":"Il manque quelques ingrédients"}</p><div class="progress"><i style="width:${r.match}%"></i></div></div><span class="badge">${r.match}%</span></div>`).join("")}</section>`}
function menu(){return `<button class="primary pressable" onclick="generateMenu()">✨ Générer mon menu</button><section class="section"><div class="week">${state.menu.map((d,i)=>`<div class="day"><b>${d[0]}</b><div class="meal" onclick="editMeal(${i},1)">☀️ ${d[1]}</div><div class="meal" onclick="editMeal(${i},2)">🌙 ${d[2]}</div></div>`).join("")}</div></section><button class="secondary pressable" style="width:100%" onclick="shopping()">🛒 Générer la liste de courses</button>`}
function profile(){return `<section class="hero"><h2>Ma cuisine ❤️</h2><p>${state.favorites.size} favoris · ${state.liked.size} recettes aimées</p><div class="emoji">👨‍🍳</div></section><section class="section"><div class="row-card"><div class="food-icon">❤️</div><div class="grow"><h3>Mes favoris</h3><p>${state.favorites.size} recette(s)</p></div></div><div class="row-card"><div class="food-icon">👍</div><div class="grow"><h3>J'ai aimé</h3><p>${state.liked.size} recette(s)</p></div></div><div class="row-card"><div class="food-icon">📚</div><div class="grow"><h3>Mes recettes privées</h3><p>Bientôt : import par scan</p></div></div></section>`}
function assistant(){let m=state.chat.length?state.chat:`<div class="chat-bubble">Bonjour ! 👋 Je peux t'aider à choisir un repas, utiliser ton frigo ou trouver une idée rapide.</div>`;return `<div class="chat">${m}</div><section class="section"><div class="suggestions"><button class="suggest" onclick="ask('Que puis-je cuisiner avec mon frigo ?')">🧊 Avec mon frigo</button><button class="suggest" onclick="ask('Une recette rapide')">⚡ Rapide</button><button class="suggest" onclick="ask('Un repas pas cher')">💰 Petit budget</button><button class="suggest" onclick="ask('Surprends-moi')">🎲 Surprise</button></div></section><form class="chat-form" onsubmit="sendChat(event)"><input id="chatInput" placeholder="Écris ton message..."><button class="primary pressable" style="width:auto;padding:10px 15px">➤</button></form>`}
function render(){let f={home,discover,fridge,menu,profile,assistant};app.innerHTML=f[state.page]();bind()}
function bind(){document.querySelectorAll("[data-page]").forEach(e=>e.addEventListener("click",()=>setPage(e.dataset.page)))}
function openRecipe(n){let r=recipes.find(x=>x.name===n);title.textContent=r.name;subtitle.textContent="Une recette simple et gourmande";app.innerHTML=`<button class="link" onclick="setPage('discover')">← Retour</button><div class="recipe-hero">${r.emoji}</div><section class="section"><h2>${r.name}</h2><p>⭐ 4.8 · ⏱ ${r.time} · 👨‍👩‍👧 4 pers.</p><div class="actions"><button class="action ${state.liked.has(n)?'liked':''}" onclick="like('${n}')">👍 J'aime</button><button class="action" onclick="toast('Préférence enregistrée 👌')">👎 Pas pour moi</button><button class="action ${state.favorites.has(n)?'liked':''}" onclick="fav('${n}')">❤️ Favori</button></div><div class="form-card"><b>🧊 Compatible avec ton frigo</b><p>${r.match}% des ingrédients disponibles</p><div class="progress"><i style="width:${r.match}%"></i></div></div></section><section class="section"><h2>Ingrédients</h2><div class="row-card">🍝 Pâtes <span class="grow"></span>200 g <span class="badge">✓</span></div><div class="row-card">🍄 Champignons <span class="grow"></span>250 g <span class="badge">✓</span></div><div class="row-card">🥛 Crème fraîche <span class="grow"></span>20 cl <span class="badge warning">Manque</span></div></section><button class="primary pressable" onclick="cookMode('${n}')">👨‍🍳 Commencer à cuisiner</button>`}
function like(n){state.liked.has(n)?state.liked.delete(n):state.liked.add(n);save();toast(state.liked.has(n)?"👍 J'aime !":"Like retiré");openRecipe(n)}
function fav(n){state.favorites.has(n)?state.favorites.delete(n):state.favorites.add(n);save();toast(state.favorites.has(n)?"❤️ Ajouté aux favoris":"Favori retiré");openRecipe(n)}
function cookMode(n){title.textContent="Mode cuisine 👨‍🍳";subtitle.textContent="Étape 2 sur 6";app.innerHTML=`<div class="recipe-hero" style="height:340px;background:linear-gradient(180deg,#493830,#171313)">🍄</div><section class="section" style="text-align:center"><h2>Fais revenir les champignons</h2><p>Dans une poêle avec un filet d'huile d'olive pendant 5 minutes.</p><div style="font-size:54px;font-weight:900;margin:24px" id="timer">05:00</div><button class="secondary pressable" onclick="startTimer()">▶ Démarrer</button></section><button class="primary pressable" onclick="toast('Bravo ! Étape suivante 🎉')">Étape suivante →</button>`}
function startTimer(){let s=300,e=document.querySelector("#timer");clearInterval(window.timer);window.timer=setInterval(()=>{s--;e.textContent=`${String(s/60|0).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(s<=0){clearInterval(window.timer);toast("⏰ Temps écoulé !")}},1000)}
function addFood(x){x=x.trim();if(x){state.fridge.push("🥕 "+x);save();toast("Ajouté au frigo 🧊");render()}}
function removeFood(i){state.fridge.splice(i,1);save();toast("Aliment retiré");render()}
function showSuggestions(){title.textContent="Suggestions ✨";subtitle.textContent="Des idées selon ton frigo";app.innerHTML=sugg();bind()}
function surprise(){openRecipe(recipes[Math.floor(Math.random()*recipes.length)].name)}
function generateMenu(){let p=prompt("Pour combien de personnes ?",2);if(!p)return;state.menu.forEach((d,i)=>{d[1]=recipes[i%recipes.length].emoji+" "+recipes[i%recipes.length].name;d[2]=recipes[(i+2)%recipes.length].emoji+" "+recipes[(i+2)%recipes.length].name});save();toast(`✨ Menu généré pour ${p} personne(s)`);render()}
function editMeal(i,j){let x=prompt("Modifier ce repas :",state.menu[i][j]);if(x){state.menu[i][j]=x;save();render()}}
function shopping(){toast("🛒 Liste de courses générée !")}
function ask(q){state.chat+=`<div class="chat-bubble user">${q}</div>`;let l=q.toLowerCase(),a=l.includes("frigo")?"Avec ton frigo, je te conseille le poulet curry coco 🍛 : il correspond très bien à tes ingrédients.":l.includes("rapide")?"Je te propose le bowl quinoa avocat 🥗, prêt en 20 minutes.":l.includes("cher")?"Les pâtes crémeuses aux champignons 🍝 sont simples et économiques.":"Je te propose de découvrir le poulet curry coco 🍛 !";setTimeout(()=>{state.chat+=`<div class="chat-bubble">${a}</div>`;render()},280);render()}
function sendChat(e){e.preventDefault();let x=document.querySelector("#chatInput").value.trim();if(x)ask(x)}
function search(q){q=q.toLowerCase();if(!q){render();return}let a=recipes.filter(r=>r.name.toLowerCase().includes(q));app.innerHTML=`<h2>Résultats</h2><div class="grid">${a.length?a.map(card).join(""):`<div class="empty">Aucune recette trouvée 😕</div>`}</div>`}
function filterCat(c){let a=recipes.filter(r=>r.cat===c);app.innerHTML=`<button class="link" onclick="setPage('discover')">← Retour</button><section class="section"><h2>${c}</h2><div class="grid">${a.length?a.map(card).join(""):`<div class="empty">Cette catégorie sera bientôt remplie 🍋</div>`}</div></section>`}
document.querySelector("#themeBtn").onclick=()=>{state.dark=!state.dark;document.body.classList.toggle("dark",state.dark);document.querySelector("#themeBtn").textContent=state.dark?"☀️":"🌙";save()};
document.body.classList.toggle("dark",state.dark);document.querySelector("#themeBtn").textContent=state.dark?"☀️":"🌙";render();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
